In [1]:
import pandas as pd
from bs4 import BeautifulSoup
from splinter import Browser
from webdriver_manager.chrome import ChromeDriverManager

In [2]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

====== WebDriver manager ======
Current google-chrome version is 92.0.4515
Get LATEST driver version for 92.0.4515
Driver [C:\Users\HP\.wdm\drivers\chromedriver\win32\92.0.4515.107\chromedriver.exe] found in cache

In [3]:
olympics_facts=pd.read_html("https://en.wikipedia.org/wiki/List_of_multiple_Olympic_gold_medalists")[0]
print(olympics_facts)

     No.          Athlete         Nation         Sport      Years   Games  \
0      1   Michael Phelps  United States      Swimming  2004–2016  Summer
1      2  Larisa Latynina   Soviet Union    Gymnastics  1956–1964  Summer
2      3      Paavo Nurmi        Finland     Athletics  1920–1928  Summer
3      4       Mark Spitz  United States      Swimming  1968–1972  Summer
4      5       Carl Lewis  United States     Athletics  1984–1996  Summer
..   ...              ...            ...           ...        ...     ...
216  182     Tobias Wendl        Germany          Luge  2014–2018  Winter
217  182  Serena Williams  United States        Tennis  2000–2012  Summer
218  182    Bärbel Wöckel   East Germany     Athletics  1976–1980  Summer
219  182     Zhang Yining          China  Table tennis  2004–2008  Summer
220  182              NaN            NaN           NaN        NaN     NaN

    Gender  Gold  Silver  Bronze  Total
0        M  23.0     3.0     2.0   28.0
1        F   9.0     5.0     4.0   18.0
2        M   9.0     3.0     0.0   12.0
3        M   9.0     1.0     1.0   11.0
4        M   9.0     1.0     0.0   10.0
..     ...   ...     ...     ...    ...
216      M   4.0     0.0     0.0    4.0
217      F   4.0     0.0     0.0    4.0
218      F   4.0     0.0     0.0    4.0
219      F   4.0     0.0     0.0    4.0
220    NaN   NaN     NaN     NaN    NaN

[221 rows x 11 columns]

In [4]:
olympics_facts.columns=["No.","Athlete","Nation", "Sport", "Years", "Games", "Gender", "Gold", "Silver", "Bronze", "Total"]
olympics_facts.set_index("No.",inplace=True)
olympics_facts

,Athlete,Nation,Sport,Years,Games,Gender,Gold,Silver,Bronze,Total
No.,,,,,,,,,,
1,Michael Phelps,United States,Swimming,2004–2016,Summer,M,23.0,3.0,2.0,28.0
2,Larisa Latynina,Soviet Union,Gymnastics,1956–1964,Summer,F,9.0,5.0,4.0,18.0
3,Paavo Nurmi,Finland,Athletics,1920–1928,Summer,M,9.0,3.0,0.0,12.0
4,Mark Spitz,United States,Swimming,1968–1972,Summer,M,9.0,1.0,1.0,11.0
5,Carl Lewis,United States,Athletics,1984–1996,Summer,M,9.0,1.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...
182,Tobias Wendl,Germany,Luge,2014–2018,Winter,M,4.0,0.0,0.0,4.0
182,Serena Williams,United States,Tennis,2000–2012,Summer,F,4.0,0.0,0.0,4.0
182,Bärbel Wöckel,East Germany,Athletics,1976–1980,Summer,F,4.0,0.0,0.0,4.0
182,Zhang Yining,China,Table tennis,2004–2008,Summer,F,4.0,0.0,0.0,4.0
182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
olympics_facts.dropna(inplace=True)

In [6]:
olympics_facts['Athlete'].replace({'Ahn Hyun-SooViktor Ahn':'Viktor Ahn'}, inplace=True)

olympics_facts['Nation'].replace({'South Korea Russia':'Russia',
                                 'East Germany Germany': 'Germany',
                                 'Russia ROC': 'Russia',
                                 'Unified Team Russia': 'Russia',
                                 'Unified Team Belarus': 'Belarus',
                                 'United Team of Germany West Germany':'Germany',
                                 'Soviet UnionÂ Unified Team':'Soviet Union',
                                 'Unified TeamÂ Russia':'Russia',
                                 'West GermanyÂ Germany':'Germany'}, inplace=True)


olympics_facts['Nation'] = olympics_facts['Nation'].str.replace(r'[^\x00-\x7f]', '')



olympics_facts['Sport'].replace({'Swimming, Water polo':'Swimming',
                                 'Water polo, Swimming': 'Water polo',
                                 'Gymnastics, Wrestling': 'Gymnastics',
                                'Table tennis': 'Table Tennis'}, inplace=True)

In [7]:
olympics_facts

,Athlete,Nation,Sport,Years,Games,Gender,Gold,Silver,Bronze,Total
No.,,,,,,,,,,
1,Michael Phelps,United States,Swimming,2004–2016,Summer,M,23.0,3.0,2.0,28.0
2,Larisa Latynina,Soviet Union,Gymnastics,1956–1964,Summer,F,9.0,5.0,4.0,18.0
3,Paavo Nurmi,Finland,Athletics,1920–1928,Summer,M,9.0,3.0,0.0,12.0
4,Mark Spitz,United States,Swimming,1968–1972,Summer,M,9.0,1.0,1.0,11.0
5,Carl Lewis,United States,Athletics,1984–1996,Summer,M,9.0,1.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...
182,Thomas Wassberg,Sweden,Cross-country skiing,1980–1988,Winter,M,4.0,0.0,0.0,4.0
182,Tobias Wendl,Germany,Luge,2014–2018,Winter,M,4.0,0.0,0.0,4.0
182,Serena Williams,United States,Tennis,2000–2012,Summer,F,4.0,0.0,0.0,4.0
182,Bärbel Wöckel,East Germany,Athletics,1976–1980,Summer,F,4.0,0.0,0.0,4.0
182,Zhang Yining,China,Table Tennis,2004–2008,Summer,F,4.0,0.0,0.0,4.0

In [8]:
olympics_facts['Gold'] = olympics_facts['Gold'].astype(int)
olympics_facts['Silver'] = olympics_facts['Silver'].astype(int)
olympics_facts['Bronze'] = olympics_facts['Bronze'].astype(int)
olympics_facts['Total'] = olympics_facts['Total'].astype(int)

olympics_facts

,Athlete,Nation,Sport,Years,Games,Gender,Gold,Silver,Bronze,Total
No.,,,,,,,,,,
1,Michael Phelps,United States,Swimming,2004–2016,Summer,M,23,3,2,28
2,Larisa Latynina,Soviet Union,Gymnastics,1956–1964,Summer,F,9,5,4,18
3,Paavo Nurmi,Finland,Athletics,1920–1928,Summer,M,9,3,0,12
4,Mark Spitz,United States,Swimming,1968–1972,Summer,M,9,1,1,11
5,Carl Lewis,United States,Athletics,1984–1996,Summer,M,9,1,0,10
...,...,...,...,...,...,...,...,...,...,...
182,Thomas Wassberg,Sweden,Cross-country skiing,1980–1988,Winter,M,4,0,0,4
182,Tobias Wendl,Germany,Luge,2014–2018,Winter,M,4,0,0,4
182,Serena Williams,United States,Tennis,2000–2012,Summer,F,4,0,0,4
182,Bärbel Wöckel,East Germany,Athletics,1976–1980,Summer,F,4,0,0,4
182,Zhang Yining,China,Table Tennis,2004–2008,Summer,F,4,0,0,4

In [9]:
olympics_facts.to_csv("../Output/Multi_Winning_Athletes.csv", encoding='utf-8')